version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 5

  - package-ecosystem: "npm"
    directory: "/platform/services/fee-router"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 5

  - package-ecosystem: "npm"
    directory: "/platform/services/cli-launcher"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 5
