name: "Setup action"
description: "Setup repository and install deps"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v5
      with:
        node-version: 22
        cache: "npm"
    - name: Install deps
      shell: bash
      run: npm ci
